[package]
name = "amsterdammetje-article"
version = "0.1.0"
entrypoint = "uva.typ"
authors = ["qu1ncyk <https://github.com/qu1ncyk>"]
license = "MPL-2.0"
description = "University of Amsterdam Computer Science article template"
repository = "https://github.com/qu1ncyk/uva-article-typst"
categories = ["report"]
disciplines = ["computer-science"]
keywords = ["uva", "article", "informatica"]
